name: test
on:
    pull_request:
        types:
            - opened
    workflow_dispatch:
    push:
        branches:
            - master
        paths-ignore:
            - '.github/**'
                

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            - name: Set up Node.js
              uses: actions/setup-node@v5
              with:
                node-version: '24'
                cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
            - run: |
                mkdir -p test-results
                echo '{"testResults": "All tests passed!"}' > test-results/test-results.json
            - name: upload test results
              uses: actions/upload-artifact@v7
              with:
                name: test-results
                path: test-results
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Download test results
              uses: actions/download-artifact@v7
              with:
                name: test-results
            - name: Checkout code
              uses: actions/checkout@v5
            - name: Set up Node.js
              uses: actions/setup-node@v5
              with:
                node-version: '24'
                cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Deploy to production
              run: npm run build
            - name: Notify deployment
              run: echo "Deployment completed successfully!"